# Generated by Django 5.1 on 2024-09-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publication_app', '0007_rename_image_post_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('post', models.ManyToManyField(related_name='tags', to='publication_app.post')),
            ],
        ),
    ]
