# Generated by Django 5.1 on 2024-09-04 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments_app', '0002_alter_comment_post_alter_comment_user'),
        ('likes_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='comments_app.comment'),
            preserve_default=False,
        ),
    ]
