# Generated by Django 5.1 on 2024-08-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication_app', '0003_post_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
