# Generated by Django 5.1 on 2024-09-03 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication_app', '0006_alter_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='file',
        ),
    ]
